# Generated by Django 4.2 on 2024-08-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
