# Generated by Django 4.2.2 on 2025-02-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_dob'),
        ('patient', '0009_alter_patient_address_alter_patient_email_and_more'),
    ]

    operations = [
    ]
