# Generated by Django 4.2 on 2024-08-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_billing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='gender',
        ),
    ]
