# Generated by Django 4.2 on 2024-08-16 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_rename_date_of_birth_patient_dob_and_more'),
        ('base', '0005_remove_appointment_address_remove_appointment_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_patient', to='patient.patient'),
        ),
    ]
