# Generated by Django 4.2 on 2024-08-16 12:24

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_billing_patient_alter_emergencycontact_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='billing_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=10, prefix=''),
        ),
    ]
