# Generated by Django 4.2 on 2024-08-16 15:12

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_appointment_date_appointment_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=10, prefix=''),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
