# Generated by Django 4.2 on 2024-08-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_appointment_appointment_id_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='pharmacist',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='date',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
    ]
