# Generated by Django 4.2.2 on 2025-02-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_appointment_doctor_appointment_patient_and_more'),
        ('base', '0012_alter_appointment_status_alter_billing_status'),
    ]

    operations = [
    ]
