# Generated by Django 4.2 on 2024-08-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
