# Generated by Django 4.2.2 on 2025-02-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_next_available_appointment_date'),
        ('doctor', '0007_alter_doctor_user'),
    ]

    operations = [
    ]
